### ISSUE TITLE
[Feature Request] Adding mTLS (client cert validation) support to Chisel

### ISSUE THREAD

**Issue by wxia20** [jpillora/chisel#184]
Hi, @jpillora 

First let me say this is a great project and I'm so glad you pull this off with so many features, neat and in high quality. Great work! I'm using Chisel to tunnel through my TCP and HTTP based services running in the cloud without VPN or SSH, definitely my tool of choice.

When using Chisel, I want to enforce the security on server side by adding mTLS (client certificate validation). I'm not comfortable to expose Chisel server on internet without decent protection. 

To add mTLS support, basically Chisel client needs to send client cert and Chisel server needs to validate client cert using CA chain which signed the client cert. Do you think this feature make sense and is this something you've supported or on the Chisel road map?

Over the weekend I did some experiment on the code base and was able to make it work roughly...

Let me know your thoughts on this.

Cheers! - Will

**Comment by jpillora** [comment]
Thank you :)

Sure, I’d be happy to add mTLS. Do you have a PR?

On my mobile at the moment though I’m thinking we’ll need to add flags

Server
--ca  a path to a PEM encoded CA certificate bundle used to validate client connections. The provided CA certificates will be used instead of the system roots.

Client
--key   a path to a PEM encoded private key used for client authentication (mTLS).

--cert   a path to a PEM encoded certificate matching the provided private key. The certificate must have client authentication enabled (mTLS).

**Comment by wxia20** [comment]
I can put it into a PR. I can't share the real certs but will generate the self signed certs and test cases.

**Comment by wxia20** [comment]
PR created here: [mTLS authentication feature](https://github.com/jpillora/chisel/pull/185)
@jpillora please review and provide your feedback.

**Comment by jpillora** [comment]
Thanks! Hoping to release 1.7.0 stable soon
