### ISSUE TITLE
Autoroute like meterpreter

### ISSUE THREAD

**Issue by nodauf** [jpillora/chisel#237]
A autoroute feature like the one on metasploit would be really great.
For example:
1. For each client many clients are connected to the chisel server configure on a reverse proxy socks
2. We register a route for a specific session (i.e: `route 192.168.1.0/24 session 1`
3. On chisel server, there is only one port available for the socks5 and chisel we decide on which client the traffic will be sent according to the routing table.

**Comment by nodauf** [comment]
I am working on it

**Comment by nodauf** [comment]
Did a project to manage multiple socks connection https://github.com/nodauf/Go-RouterSocks

**Comment by vetch101** [comment]
Looks good!
This is a challenge I've experienced, too. 
Thanks.

A related problem I've seen is where you're working with multiple client sites and want a single port per client, but sometimes the socks connection does not connect to a remote service in the same way that a direct port forward does. 

While this is (obviously) out of scope for your issue, it would be neat to be able to "reconfigure" the connection on the client side from the server side.

I'm thinking something along the lines of, if on the 127.0.0.1:1081 socks connection routing to 192.168.1.0/24, there was a particular service running on port 1001 on 192.168.1.57 which did not behave as expected over socks, the server side could send a request to the client to update the mapping of the server so that 127.0.0.1:1081 now forwarded to 192.168.1.57:1001 (instead of the socks connection) in order to access the necessary service...
... and then the server side could issue a request to switch the mapping back to a socks connection.

Clearly, you would need some kind of client-side authentication that controlled what the server side was allowed to open access to, but it seems like this could assist in those instances where a service fails to proxy correctly over socks.

**Comment by nodauf** [comment]
Thank you for your feedback.

Using port forwarding without socks and reconfigure the chisel client is out of scope for this project. The main idea is to keep as simple as possible so It can be used with any socks server.  And from what I know reconfiguring the chisel client would need to update the chisel project as well.

**Comment by jpillora** [comment]
See https://github.com/jpillora/chisel/issues/3 issue 3 from 2015. @nodauf is correct, as you can see from this issue, chisel could be used to forward any port dynamically, however that would make chisel a VPN, and definitely out of scope

**Comment by vetch101** [comment]
@nodauf - understood; thanks.

@jpillora - Thanks. 
I was referring to the routing mentioned in nodauf's Go-RouterSocks https://github.com/nodauf/Go-RouterSocks/raw/main/images/schema.png. 

For clarity, I wasn't really thinking about forwarding all ports dynamically, but rather reconfiguring the remotes from the server end. 

So let's say the initial connection is:

chisel client https://remote.chisel.com R:127.0.0.1:5001:192.168.1.1:443

From the server end, you could update that remote to the equivalent of:

chisel client https://remote.chisel.com R:127.0.0.1:5001:192.168.1.2:22 or socks or whatever.

I appreciate this may be out of scope, but I think it's a different approach to Issue 3.
