### ISSUE TITLE
Can UDP protocol be transported as https traffic?

### ISSUE THREAD

**Issue by saintdev2** [jpillora/chisel#68]
Can we be able to transport UDP traffic between android/ios client and server to bypass VoIP censorship? as local isp's start dropping packets as soon as they identify udp traffic. Your comments will be highly appreciated.

**Comment by saintdev2** [comment]
can you please let me know what needs to be done or how it can be achieved plz. Your reply will be highly appreciated. Thanks

**Comment by jpillora** [comment]
Actually, this is quite a bit harder than just adding a UDP listener since SSH relies on TCP and chisel is fully dependant on the SSH protocol.

You could use https://github.com/xtaci/kcp-go to create a TCP-like connection over UDP, then add chisel on top of that. Though in your case, I'd recommend just using https://github.com/xtaci/kcptun instead of chisel.
