### ISSUE TITLE
Can I utilize multiple dynos in Heroku?

### ISSUE THREAD

**Issue by 0xbkt** [jpillora/chisel#83]
I ran across chisel today and had some spare time to try it on Heroku.

I have 100 dynos running with different IPs but when I connect my app via Heroku Router with chisel client, it simply establishes a conn with a random dyno. I want to take advantage of multiple IPs attached to my dynos. Is there a way to instruct chisel to establish a new conn whenever a req hits the local socks, in a multitenant environment avoiding the possibility of overlapping reqs?

Thanks.

**Comment by jpillora** [comment]
No, this functionality would need to be added

**Comment by 0xbkt** [comment]
@jpillora Do you have any tip for me to do it myself? Where should I start?

**Comment by DashLt** [comment]
There'll be a lot of overhead, but if you pre-spawn connections on all 100 dynos, you can use NGINX as a load-balancer. https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

(alternatively there's probably a way to have nginx start the connection when the SOCKS is hit, but don't ask me about it)

**Comment by 0xbkt** [comment]
@DashLt Can you elaborate a little more on this? Heroku's web router already picks a random dyno from “web” dynos formation. I don't think there is a way to intercommunicate among dynos in same formation.

**Comment by DashLt** [comment]
Are you trying to randomize the IP per connection, or something else?

**Comment by 0xbkt** [comment]
@DashLt exactly that.

**Comment by pro-src** [comment]
He's trying to control a bot network where each command should go to exactly one bot but instead some bots receive the, would be one-off, command multiple times. :laughing:

The solution would be to reconfigure the load balancer but you can't. Also, you can't simply run your own load balancer on a dyno since all new connections would be routed through the external load balancer first.

Quoting the docs: 

https://devcenter.heroku.com/articles/http-routing#routing
> Inbound requests are received by a load balancer that offers SSL termination. From here they are passed directly to a set of routers.
>
> The routers are responsible for determining the location of your application’s web dynos and forwarding the HTTP request to one of these dynos.

https://devcenter.heroku.com/articles/dynos#common-runtime-networking
> The Common Runtime provides strong isolation by firewalling all dynos off from one another. The only traffic that can reach a dyno is web requests forwarded from the router to web processes listening on the port number specified in the $PORT environment variable. Worker and one-off dynos cannot receive inbound requests.

If they're firewalled off from one another, how would a load balancer running on one of these dynos forward the connection to a specific dyno? It wouldn't, not without a reverse proxy server because a dyno is only accessible via Heroku's routers.

A reverse proxy setup would look something like:
`dyno / reverse proxy server > custom load balancer < client`

Except it doesn't make sense to have one of the dynos act as a load balancer when every new connection is going to be processed by heroku's routers. Again, there is no `dyno > dyno`, although you could `dyno > Heroku's routers > random dyno`, it's not helpful.

Consider:
`client > heroku's load balancer > routers > random dyno` (which one is the load balancer?)

Even if they weren't, you can't treat the dynos as apps with separate configurations. They're identical workers of a cluster. You'd need a separate app to serve as the load balancer that both dynos and clients will connect through. I guess there is an exception, if you have a separate app to determine who wins a race to become the master and tells all the losers to connect to the winner.

Alternatively, you could setup a load balancer on the client and have all 100 dynos act as reverse proxies and connect directly to the client.

**Comment by 0xbkt** [comment]
There is no way other than reverse tunneling from inside dynos to a central server, so having exposed server to pipe packets from client to dynos via those active tunnels. Now I realize that this was not actually an issue. It's too platform specific. Hency why I'm closing this.
